### PR TITLE
use ansible_distribution instead of ansible_os_family

### LINKED ISSUE #33: Installation issue on Fedora 36
Fedora 36 is being recognised as redhat in main task of install_ansible_rulebook therefore it try to include task install_redhat.yml which doesn't exist.

{{ ansible_os_family }} returns redhat which should be fedora

https://github.com/ansible/event-driven-ansible/blob/445579834ceb418ba5f34befe3ef566ad7475458/roles/install_ansible_rulebook/tasks/main.yml

**ERROR**
`TASK [ansible.eda.install_ansible_rulebook : Install for RedHat] ********************************************************************************************************************
fatal: [localhost]: FAILED! => {"reason": "Could not find or access '/home/gunjankumar/.ansible/collections/ansible_collections/ansible/eda/playbooks/install_redhat.yml' on the Ansible Controller."}`

### PR DESCRIPTION
**Pull request by konstruktoid**
This PR:
- uses `ansible_distribution` instead of `ansible_os_family`
- closes #33 

Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

### CODE REVIEW

**Comment by konstruktoid** [comment]
will do

**Comment by konstruktoid** [comment]
should we use `install_macosx"` instead of "Darwin" as well? Just to be consistent.
Or  perhaps `install_<family>.yml` with distribution blocks if needed?

**Comment by Alex-Izquierdo** [comment]
Yes, the file should be renamed to whatever returns for ansible_distribution in mac os platforms. I don't have a mac near right now. @josephpisciotta could you look it?

**Comment by konstruktoid** [comment]
will use `ansible_distribution` then

**Review by ttuffin — APPROVED** [review]

**Review by Alex-Izquierdo — APPROVED** [review]

**Pull request merged**
