### PR TITLE
Ensure modules are idempotent

### PR DESCRIPTION
**Pull request by alinabuzachis**
Ensure modules are idempotent

### CODE REVIEW

**Review by Akasurde — COMMENTED** [review]
Do you think we need a changelog for this? Rest LGTM

**Comment by Alex-Izquierdo** [comment]
> Do you think we need a changelog for this? Rest LGTM

@Akasurde how the change log works? I thought it would be generated automatically at the release time. If we need to do something on purpose I think https://github.com/ansible/event-driven-ansible/pull/322 should have also to update the change log.

**Comment by Akasurde** [comment]
@Alex-Izquierdo 
See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example for comment. These fragments will create changelog at the time of release.

**Comment by alinabuzachis** [comment]
> @Alex-Izquierdo See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example for comment. These fragments will create changelog at the time of release.

The problem is that I do not see anymore the changelogs folder.

**Comment by Akasurde** [comment]
> > @Alex-Izquierdo See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example for comment. These fragments will create changelog at the time of release.
> 
> The problem is that I do not see anymore the changelogs folder @Akasurde .


Seems like GitHub release is managing the changelog. NVM, drop this review request comment.

**Review by Akasurde — APPROVED** [review]

**Review by Alex-Izquierdo — APPROVED** [review]

**Pull request merged**
