### PR TITLE
False positive output in tox linter checks

### PR DESCRIPTION
**Pull request by ccamacho**
This commit:
- Makes easier to test individually each commit by allowing to run the GitHub actions on each fork push and pull request.
- Remove the appended path in the ruff tox check that breaks it to parse recursivelly all the python code.

TODO: This should be applied to all the other tox check to make them show correctly all the linters errors.

Closes: #145

### CODE REVIEW

**Comment by ccamacho** [comment]
This is expected to make the tox check to fail, additional PRs should be submitted fo fix all the lint nits.

**Comment by ttuffin** [comment]
I am not sure about running all tests for every push to all branches, it could get a little noisy in my opinion. @Alex-Izquierdo, thoughts?

**Comment by ccamacho** [comment]
> I am not sure about running all tests for every push to all branches, it could get a little noisy in my opinion. @Alex-Izquierdo, thoughts?

@ttuffin thanks for the feedback!! Yeah, the thing is that in your fork, the tests will run whenever you create a branch, make your changes, and testing them before pushing a PR. Also we are not running any check i.e. when merging things in stable/1.0 which might be useful to detect things that might break there.

**Comment by Alex-Izquierdo** [comment]
Hi @ccamacho thanks for the contribution, unfortunately there are still checks in ruff that are not passing.

**Pull request closed without merging**
