### PR TITLE
Rabbitmq event source

### LINKED ISSUE #182: Add RabbitMQ as an event source
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that ansible-rulebook is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

It would be great to have RabbitMQ as an event source

### PR DESCRIPTION
**Pull request by sc68cal**
This fixes #182

### CODE REVIEW

**Comment by Alex-Izquierdo** [comment]
Hello @sc68cal,

First, I would like to express our most sincere thanks for your time. Unfortunately, we have decided that a RabbitMQ plugin does not align with the scope of our official collection. This is similar to what I explained a month ago in response to another pull request with the same proposal, which can be found [here](https://github.com/ansible/event-driven-ansible/pull/59#issuecomment-1739690978)

We invite you to share this valuable contribution through your own collection in the public [Galaxy repository](https://galaxy.ansible.com).

**Comment by Alex-Izquierdo** [comment]
Hi @sc68cal I have seen you have pushed new commits in this PR. As I commented in my previous comment and also in the [issue](https://github.com/ansible/event-driven-ansible/issues/182) related we are not going to merge this PR. I will close it to avoid misunderstandings and I encourage to you to share this valuable plugin through your own collection. Thanks again for your time and effort.

**Comment by sc68cal** [comment]
@Alex-Izquierdo You do not appear to have answered my question posted in #182 where I disagree with your conclusion. What form of communication are you available on to discuss?

**Comment by Alex-Izquierdo** [comment]
Sorry for the misunderstanding. Let's continue the discussion in https://github.com/ansible/event-driven-ansible/issues/182

**Pull request closed without merging**
