### PR TITLE
Add HMAC verification support to webhook plugin

### PR DESCRIPTION
**Pull request by lszomor**
Add HMAC verification support for webhook plugin.

**Rationale**
For security reasons, payloads originating from services supporting HMAC signatures, such as GitHub, Bitbucket, and Dropbox, should be verifiable.

**Implementation details**
The current implementation supports hex and base64 signature formats. 
The argument defaults are aligned with GitHub defaults. 
The HMAC verification can be used in addition to the existing Bearer token validation.

### CODE REVIEW

**Review by Alex-Izquierdo — DISMISSED** [review]
It looks like really good. Thank you very much.

**Comment by lszomor** [comment]
@Alex-Izquierdo Thank you!

**Comment by lszomor** [comment]
Hi,

I've merged the main branch and fixed the new tox issues.

**Comment by Alex-Izquierdo** [comment]
Hi @lszomor Can you remove all the changes that are out of the scope of this PR? You should not have any issue with linting checks after merge https://github.com/ansible/event-driven-ansible/pull/167

Thanks for everything.

**Comment by Alex-Izquierdo** [comment]
sure, thank you very much. @lszomor

**Review by Alex-Izquierdo — APPROVED** [review]

**Review by bzwei — APPROVED** [review]

**Pull request merged**
