### PR TITLE
journald: basic ruff formating

### PR DESCRIPTION
**Pull request by konstruktoid**
Ref https://github.com/ansible/event-driven-ansible/pull/135

### CODE REVIEW

**Comment by konstruktoid** [comment]
Will fix line length later today

**Review by Alex-Izquierdo — DISMISSED** [review]
LGTM

**Comment by konstruktoid** [comment]
All checks passed :+1:

**Comment by ccamacho** [comment]
Hi! all the fixes LGTM but there are still a few things here, I just fetched/rebased #139 on top of #138 and this is part of the output:

```

linters: commands[0]> bash -c 'echo '"'"'==> Installing Event Driven Ansible...'"'"''
==> Installing Event Driven Ansible...
linters: commands[1]> bash -c 'ansible-galaxy collection build -v --force --output-path releases/ && ansible-galaxy collection install --force --force-with-deps releases/ansible-eda-$(cat ./galaxy.yml | shyaml get-value version).tar.gz'
No config file found; using defaults
Created collection for ansible.eda at /home/ccamacho/dev/event-driven-ansible/releases/ansible-eda-1.3.8.tar.gz
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'ansible.eda:1.3.8' to '/home/ccamacho/.ansible/collections/ansible_collections/ansible/eda'
ansible.eda:1.3.8 was installed successfully

linters: commands[2]> bash -c 'ruff check --exclude .tox --select ALL --ignore INP001 . || true'
.
.
.
extensions/eda/plugins/event_source/journald.py:32:11: ANN201 Missing return type annotation for public function `main`
extensions/eda/plugins/event_source/journald.py:32:11: D103 Missing docstring in public function
extensions/eda/plugins/event_source/journald.py:58:11: D101 Missing docstring in public class
extensions/eda/plugins/event_source/journald.py:59:19: ANN201 Missing return type annotation for public function `put`
extensions/eda/plugins/event_source/journald.py:59:19: D102 Missing docstring in public method
extensions/eda/plugins/event_source/journald.py:59:23: ANN101 Missing type annotation for `self` in method
extensions/eda/plugins/event_source/journald.py:59:29: ANN001 Missing type annotation for function argument `event`
extensions/eda/plugins/event_source/journald.py:60:13: T201 `print` found
.
.
.
.
.
.
.
Found 739 errors.

linters: commands[3]> bash -c 'find . -not -path "./.tox/*" -and -name "*.py" -print0 | xargs -0 darglint -v 1 -s numpy -z full || true'
.
.
.
linters: commands[4]> bash -c 'find . -not -path "./.tox/*" -and -name "*.py" -print0 | xargs -0 pylint || true'
.
.
.
************* Module journald
extensions/eda/plugins/event_source/journald.py:32:0: C0116: Missing function or method docstring (missing-function-docstring)
extensions/eda/plugins/event_source/journald.py:58:4: C0115: Missing class docstring (missing-class-docstring)
extensions/eda/plugins/event_source/journald.py:59:8: C0116: Missing function or method docstring (missing-function-docstring)
extensions/eda/plugins/event_source/journald.py:58:4: R0903: Too few public methods (1/2) (too-few-public-methods)
.
.
.

linters: commands[5]> bash -c 'flake8 --exclude .tox || true'
.
./tests/integration/event_source_url_check/test_url_check_source.py:45:1: DAR101 Missing parameter(s) in Docstring: - endpoint
.
  linters: OK (14.89=setup[0.06]+cmd[0.01,1.18,0.18,0.37,12.53,0.56] seconds)
  congratulations :) (14.95 seconds)
```

There are still a few things to fix before it passes.

I would vote first to have the lint check merged (but disabled like in #138) so it is possible to verify that the styling is actually consistent. Future tests can be easily verified and merged.

**Comment by konstruktoid** [comment]
Will fix during the weekend, and use `ruff check --exclude .tox --select ALL --ignore INP001 .` instead of the current GitHub tests

**Comment by konstruktoid** [comment]
rebased

**Comment by konstruktoid** [comment]
Failing tox test: https://github.com/ansible/event-driven-ansible/pull/149

**Review by ttuffin — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
Hi @konstruktoid, it looks that the mentioned PR that is already merged is not enough to pass the ruff checks.

**Comment by konstruktoid** [comment]
Will take a look

**Comment by konstruktoid** [comment]
All checks have passed.

ref https://github.com/astral-sh/ruff/pull/5571

**Review by ttuffin — APPROVED** [review]

**Pull request merged**
